services:
  south-americans-api:
    container_name: south-americans-api
    build:
      context: .
      dockerfile: dockerfile
      target: development
    command: yarn dev
    volumes:
      - ./src:/usr/src/app/src
      - ./.env:/usr/src/app/.env
    ports:
      - '4000:4000'
    logging:
      driver: local
    depends_on:
      - mongodb
    networks:
      - south-americans-api-network
  populate-mongdb:
    container_name: populate-mongdb-script
    build:
      context: .
      dockerfile: dockerfile
      target: development
    command: yarn populatedb
    volumes:
      - ./src:/usr/src/app/src
      - ./.env:/usr/src/app/.env
    logging:
      driver: local
    depends_on:
      - mongodb
    networks:
      - south-americans-api-network
  mongodb:
    container_name: mongodb
    image: 'mongo:4.4.0-bionic'
    ports:
      - '27017:27017'
    logging:
      driver: local
    volumes:
      - './data:/data/db'
    restart: on-failure
    networks:
      - south-americans-api-network

networks:
  south-americans-api-network:
    driver: bridge
