services:
  south-americans-api:
    build:
      target: development
    command: yarn dev
    volumes:
      - ./src:/usr/src/app/src
      - ./.env:/usr/src/app/.env
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    networks:
      - south-americans-api-network-dev
  populate-mongdb:
    build:
      target: development
    command: yarn populatedb
    volumes:
      - ./src:/usr/src/app/src
      - ./.env:/usr/src/app/.env
    depends_on:
      - mongodb
    networks:
      - south-americans-api-network-dev
  mongodb:
    container_name: mongodb-dev
    image: 'mongo:4.4.0-bionic'
    ports:
      - '27017:27017'
    volumes:
      - './data:/data/db'
    restart: on-failure
    networks:
      - south-americans-api-network-dev

networks:
  south-americans-api-network-dev:
    driver: bridge
